---
server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbpedido
    username: root
    password: Pedido2023
    driverClassName: com.mysql.cj.jdbc.Driver

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000