---
id-MS: AUT000001000001
info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
spring:
  mvc:
    servlet:
      path: /mso/pedidos
  profiles:
    active:
      - local
  jackson:
    deserialization:
      accept-float-as-int: false
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /monitor
